---
title: "**BIO214 Courseware**"
subtitle: "*Bioinformatics II*"
author:
  - "TC-tea"
date: "`r Sys.Date()`"
date-format: "YYYY.MM.DD"
output:
  quarto::quarto_document:
    default_output_format: html
    code:
      pandoc_args: ["-V", "lang=en"]
    df_print: paged
toc: true
toc-location: left
fontsize: 12pt
fontfamily: Tahoma
theme: default
comments:
  hypothesis: true
---

<head>
  <!-- Set viewport -->
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- Set styles for light and dark mode -->
  <style>
    mark {
      background-color: yellow;
    }
    .dark-mode {
      background-color: black;
      color: white;
    }
    .light-code {
      color: black;
    }
    .dark-code {
      color: white;
    }
    .quarto-output pre:not([class*="language-"]) {
      background-color: transparent;
      color: inherit;
    }
    .quarto-output pre[class*="language-"] {
      background-color: #F5F5F5;
      color: black;
    }
    .dark-mode .quarto-output pre[class*="language-"] {
      background-color: #2B2B2B;
      color: white;
    }
    /* CSS for back-to-top button */
    #back-to-top {
      position: fixed;
      bottom: 10px;
      right: 22px;
      font-size: 22px;
      border-radius: 50%;
      width: 35px;
      height: 35px;
      text-decoration: none;
    }
    /* CSS for light/dark mode toggle button */
    #myBtn {
      position: fixed;
      top: 20px;
      left: 20px;
      border: none;
      border-radius: 10px;
      padding: 8px;
      background-color: lightgray;
    }
    #myBtn:before {
      content: "☀";
    }
    .dark-mode #myBtn:before {
      content: "🌙";
    }
  </style>
</head>

<body>
  <!-- Button to toggle light/dark mode -->
  <button id="myBtn" onclick="myFunction()"></button>
  <script>
    function myFunction() {
      var element = document.body;
      element.classList.toggle("dark-mode");
      var codeBlocks = document.querySelectorAll(".quarto-output pre[class*='language-']");
      codeBlocks.forEach(function(block) {
        block.classList.toggle("light-code");
        block.classList.toggle("dark-code");
      });
    }
  </script>
  <!-- Button to scroll back to top of page -->
<a href="#" id="back-to-top" title="Back to top">🚀</a>
</body>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      message = FALSE,
                      warning = FALSE,
                      fig.align = "center")
```

👉🏻[Click to enter the BIO214 note section](../BIO214 R-session/BIO214 note.html)<br>
👉🏻[Click to enter the BIO214 R-session section](../BIO214 R-session/BIO214 R-session.html)

# **Lecture slides**

## **L2**
- [Click to enter the full separate page](https://cupoftea0315.github.io/XJTLU-BIO214-courseware/BIO214-L2_Sequencing_technologies.pdf)
<iframe src="https://cupoftea0315.github.io/XJTLU-BIO214-courseware/BIO214-L2_Sequencing_technologies.pdf" width="100%" height="400px"></iframe>

## **L3**
- [Click to enter the full separate page](https://cupoftea0315.github.io/XJTLU-BIO214-courseware/BIO214-L3_Genome_mapping.pdf)
<iframe src="https://cupoftea0315.github.io/XJTLU-BIO214-courseware/BIO214-L3_Genome_mapping.pdf" width="100%" height="400px"></iframe>

## **L4**
- [Click to enter the full separate page](https://cupoftea0315.github.io/XJTLU-BIO214-courseware/BIO214-L4_Quantification.pdf)
<iframe src="https://cupoftea0315.github.io/XJTLU-BIO214-courseware/BIO214-L4_Quantification.pdf" width="100%" height="400px"></iframe>

## **L5**
- [Click to enter the full separate page](https://cupoftea0315.github.io/XJTLU-BIO214-courseware/BIO214-L5_Normalization-I.pdf)
<iframe src="https://cupoftea0315.github.io/XJTLU-BIO214-courseware/BIO214-L5_Normalization-I.pdf" width="100%" height="400px"></iframe>

## **L6**
- [Click to enter the full separate page](https://cupoftea0315.github.io/XJTLU-BIO214-courseware/BIO214-L6_Normalization-II.pdf)
<iframe src="https://cupoftea0315.github.io/XJTLU-BIO214-courseware/BIO214-L6_Normalization-II.pdf" width="100%" height="400px"></iframe>

## **L7**
- [Click to enter the full separate page](https://cupoftea0315.github.io/XJTLU-BIO214-courseware/BIO214-L7_Pattern_identification-I.pdf)
<iframe src="https://cupoftea0315.github.io/XJTLU-BIO214-courseware/BIO214-L7_Pattern_identification-I.pdf" width="100%" height="400px"></iframe>

## **L8**
- [Click to enter the full separate page](https://cupoftea0315.github.io/XJTLU-BIO214-courseware/BIO214-L8_Pattern_identification-II.pdf)
<iframe src="https://cupoftea0315.github.io/XJTLU-BIO214-courseware/BIO214-L8_Pattern_identification-II.pdf" width="100%" height="400px"></iframe>

## **L9**
- [Click to enter the full separate page](https://cupoftea0315.github.io/XJTLU-BIO214-courseware/BIO214-L9_Knowledge_representation.pdf)
<iframe src="https://cupoftea0315.github.io/XJTLU-BIO214-courseware/BIO214-L9_Knowledge_representation.pdf" width="100%" height="400px"></iframe>

## **L10**
- [Click to enter the full separate page](https://cupoftea0315.github.io/XJTLU-BIO214-courseware/BIO214-L10_Sequence_modeling.pdf)
<iframe src="https://cupoftea0315.github.io/XJTLU-BIO214-courseware/BIO214-L10_Sequence_modeling.pdf" width="100%" height="400px"></iframe>

## **L11**
- [Click to enter the full separate page](https://cupoftea0315.github.io/XJTLU-BIO214-courseware/BIO214-L11_Assembly _variants.pdf)
<iframe src="https://cupoftea0315.github.io/XJTLU-BIO214-courseware/BIO214-L11_Assembly _variants.pdf" width="100%" height="400px"></iframe>

## **L12**
- [Click to enter the full separate page](https://cupoftea0315.github.io/XJTLU-BIO214-courseware/BIO214-L12_Coding_guide.pdf)
<iframe src="https://cupoftea0315.github.io/XJTLU-BIO214-courseware/BIO214-L12_Coding_guide.pdf" width="100%" height="400px"></iframe>

# **Chinese interpretation**

## **L2**
- [Click to enter the full separate page](https://cupoftea0315.github.io/XJTLU-BIO214-courseware/BIO214_L2.pdf)
<iframe src="https://cupoftea0315.github.io/XJTLU-BIO214-courseware/BIO214_L2.pdf" width="100%" height="400px"></iframe>

## **L3**
- [Click to enter the full separate page](https://cupoftea0315.github.io/XJTLU-BIO214-courseware/BIO214_L3.pdf)
<iframe src="https://cupoftea0315.github.io/XJTLU-BIO214-courseware/BIO214_L3.pdf" width="100%" height="400px"></iframe>

## **L4**
- [Click to enter the full separate page](https://cupoftea0315.github.io/XJTLU-BIO214-courseware/BIO214_L4.pdf)
<iframe src="https://cupoftea0315.github.io/XJTLU-BIO214-courseware/BIO214_L4.pdf" width="100%" height="400px"></iframe>

## **L5**
- [Click to enter the full separate page](https://cupoftea0315.github.io/XJTLU-BIO214-courseware/BIO214_L5.pdf)
<iframe src="https://cupoftea0315.github.io/XJTLU-BIO214-courseware/BIO214_L5.pdf" width="100%" height="400px"></iframe>

## **L6**
- [Click to enter the full separate page](https://cupoftea0315.github.io/XJTLU-BIO214-courseware/BIO214_L6.pdf)
<iframe src="https://cupoftea0315.github.io/XJTLU-BIO214-courseware/BIO214_L6.pdf" width="100%" height="400px"></iframe>

## **L7**
- [Click to enter the full separate page](https://cupoftea0315.github.io/XJTLU-BIO214-courseware/BIO214_L7.pdf)
<iframe src="https://cupoftea0315.github.io/XJTLU-BIO214-courseware/BIO214_L7.pdf" width="100%" height="400px"></iframe>

## **L8**
- [Click to enter the full separate page](https://cupoftea0315.github.io/XJTLU-BIO214-courseware/BIO214_L8.pdf)
<iframe src="https://cupoftea0315.github.io/XJTLU-BIO214-courseware/BIO214_L8.pdf" width="100%" height="400px"></iframe>

## **L9**
- [Click to enter the full separate page](https://cupoftea0315.github.io/XJTLU-BIO214-courseware/BIO214_L9.pdf)
<iframe src="https://cupoftea0315.github.io/XJTLU-BIO214-courseware/BIO214_L9.pdf" width="100%" height="400px"></iframe>

## **L10**
- [Click to enter the full separate page](https://cupoftea0315.github.io/XJTLU-BIO214-courseware/BIO214_L10.pdf)
<iframe src="https://cupoftea0315.github.io/XJTLU-BIO214-courseware/BIO214_L10.pdf" width="100%" height="400px"></iframe>

## **L11**
- [Click to enter the full separate page](https://cupoftea0315.github.io/XJTLU-BIO214-courseware/BIO214_L11.pdf)
<iframe src="https://cupoftea0315.github.io/XJTLU-BIO214-courseware/BIO214_L11.pdf" width="100%" height="400px"></iframe>





